trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'your-app-image-name'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m venv env
    source env/bin/activate
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    echo $(docker login -u $(dockerUsername) -p $(dockerPassword))
    docker build -t $(imageName) .
    docker tag $(imageName) yourcontainerregistry.azurecr.io/$(imageName):$(Build.BuildId)
    docker push yourcontainerregistry.azurecr.io/$(imageName):$(Build.BuildId)
  displayName: 'Build and push Docker image'
  env:
    dockerUsername: $(dockerUsername)
    dockerPassword: $(dockerPassword)

- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'your-azure-subscription'
    appName: 'your-app-name'
    imageName: 'yourcontainerregistry.azurecr.io/$(imageName):$(Build.BuildId)'
